import { createContext, useContext, useState } from "react";

const dict = {
  pt: {
    app_name: "CampoMark",
    nav_explore: "Explorar campos",
    nav_my_bookings: "Minhas reservas",
    nav_dashboard: "Painel do dono",
    nav_admin: "Administração",
    login: "Entrar",
    logout: "Sair",
    register: "Criar conta",
    hero_title: "Reserve seu campo em 3 passos",
    hero_subtitle: "Encontre quadras society, futsal e campos abertos perto de você. Escolha o horário, pague online e jogue.",
    hero_badge: "Agenda em tempo real · Sem conflito de horários",
    search_placeholder: "Buscar por nome ou bairro",
    all_cities: "Todas as cidades",
    all_types: "Todos os tipos",
    society: "Society",
    futsal: "Futsal",
    campo: "Campo aberto",
    from_price: "a partir de",
    book_now: "Reservar",
    no_fields: "Nenhum campo encontrado",
    per_hour: "por horário",
    choose_date: "Escolha o dia",
    choose_time: "Escolha o horário",
    available: "Disponível",
    booked: "Reservado",
    blocked: "Bloqueado",
    past: "Passado",
    summary: "Resumo da reserva",
    field: "Campo",
    date: "Data",
    time: "Horário",
    price: "Valor",
    payment_method: "Forma de pagamento",
    pay_online: "Pagar online (cartão/Pix via Stripe)",
    pay_on_site: "Pagar no local",
    confirm_booking: "Confirmar reserva",
    login_to_book: "Entre para reservar",
    what_included: "O que está incluso",
    address: "Endereço",
    cancellation_policy: "Política de cancelamento",
    cancel_policy_text: "Cancelamento até {h}h antes com reembolso de {p}%",
    my_bookings: "Minhas reservas",
    no_bookings: "Você ainda não tem reservas",
    cancel_booking: "Cancelar reserva",
    pay_now: "Pagar agora",
    status_confirmed: "Confirmada",
    status_pending_payment: "Aguardando pagamento",
    status_canceled: "Cancelada",
    booking_confirmed: "Reserva confirmada!",
    booking_cancelled: "Reserva cancelada",
    confirm_cancel_title: "Cancelar esta reserva?",
    confirm: "Confirmar",
    back: "Voltar",
    agenda: "Agenda",
    fields_tab: "Meus campos",
    revenue_tab: "Faturamento",
    subscription_tab: "Assinatura",
    add_field: "Adicionar campo",
    edit_field: "Editar campo",
    manual_block: "Bloquear horário",
    block_reason: "Motivo (manutenção, evento...)",
    block_created: "Horário bloqueado",
    block_removed: "Bloqueio removido",
    remove_block: "Remover bloqueio",
    blocks_today: "Bloqueios do dia",
    no_slots: "Sem horários configurados para este dia",
    revenue_month: "Faturamento do mês",
    bookings_count: "Reservas",
    online: "Online",
    on_site: "No local",
    subscription_status: "Status da assinatura",
    trialing: "Teste grátis",
    active: "Ativa",
    past_due: "Em atraso",
    canceled: "Cancelada",
    none: "Sem assinatura",
    trial_days_left: "dias de teste restantes",
    trial_expired: "Seu teste grátis terminou. Assine para continuar recebendo reservas.",
    subscribe_now: "Assinar agora",
    renews_at: "Renova em",
    plan_includes: "Painel completo, reservas ilimitadas e pagamentos online.",
    admin_metrics: "Métricas da plataforma",
    owners: "Donos de campo",
    active_subs: "Assinaturas ativas",
    trialing_subs: "Em teste grátis",
    past_due_subs: "Em atraso",
    fields_total: "Campos ativos",
    bookings_month: "Reservas no mês",
    mrr: "Receita mensal (MRR)",
    gmv_month: "Reservas movimentadas no mês",
    owner_name: "Dono",
    subscription: "Assinatura",
    actions: "Ações",
    deactivate: "Desativar",
    activate: "Ativar",
    inactive: "Desativado",
    demo_customer: "Entrar como Jogador",
    demo_owner: "Entrar como Dono de Arena",
    demo_admin: "Entrar como Admin",
    email: "E-mail",
    password: "Senha",
    name: "Nome",
    phone: "Telefone (WhatsApp)",
    i_am: "Eu sou",
    customer_role: "Jogador (quero reservar)",
    owner_role: "Dono de campo",
    forgot_password: "Esqueci minha senha",
    send_reset: "Enviar link de redefinição",
    reset_sent: "Se esse e-mail estiver cadastrado, enviamos o link.",
    new_password: "Nova senha",
    reset_password: "Redefinir senha",
    back_to_login: "Voltar para o login",
    payment_success: "Pagamento confirmado!",
    payment_processing: "Confirmando pagamento...",
    payment_failed: "Não foi possível confirmar o pagamento",
    payment_cancelled: "Pagamento cancelado",
    payment_cancelled_text: "Você cancelou o checkout. Sua reserva não foi confirmada.",
    go_bookings: "Ver minhas reservas",
    go_home: "Voltar ao início",
    save: "Salvar",
    delete: "Excluir",
    cancel: "Cancelar",
    field_name: "Nome do campo",
    city: "Cidade",
    neighborhood: "Bairro",
    description: "Descrição",
    photos: "Fotos (uma URL por linha)",
    slot_duration: "Duração de cada reserva (min)",
    weekly_schedule: "Grade semanal de horários",
    add_window: "Adicionar faixa",
    cancel_hours: "Cancelamento até (horas antes)",
    refund_percent: "Reembolso (%)",
    accepts: "Pagamentos aceitos",
    amenities_label: "Itens inclusos",
    field_saved: "Campo salvo!",
    field_deleted: "Campo excluído",
    booking_cancelled_by_owner: "Reserva cancelada e reembolsada (se paga online)",
    amenity_bola: "Bola",
    amenity_coletes: "Coletes",
    amenity_iluminacao: "Iluminação",
    amenity_vestiario: "Vestiário",
    amenity_arbitragem: "Arbitragem",
    amenity_estacionamento: "Estacionamento",
    amenity_churrasqueira: "Churrasqueira",
    amenity_bar: "Bar/Lanchonete",
    select_field: "Selecione o campo",
    notifications: "Notificações",
    no_notifications: "Sem notificações",
    mark_read: "Marcar como lidas",
    days: ["Seg", "Ter", "Qua", "Qui", "Sex", "Sáb", "Dom"],
    step_field: "1. Campo",
    step_time: "2. Horário",
    step_pay: "3. Pagamento",
    owner_cta_title: "Tem um campo ou quadra?",
    owner_cta_text: "Gerencie agenda, reservas e pagamentos em um só lugar. Teste grátis por 7 dias.",
    owner_cta_button: "Cadastrar meu campo",
    continue_with_google: "Continuar com Google",
    or_divider: "ou",
  },
  en: {
    app_name: "CampoMark",
    nav_explore: "Explore fields",
    nav_my_bookings: "My bookings",
    nav_dashboard: "Owner dashboard",
    nav_admin: "Administration",
    login: "Sign in",
    logout: "Sign out",
    register: "Sign up",
    hero_title: "Book your pitch in 3 steps",
    hero_subtitle: "Find society, futsal and open fields near you. Pick a time, pay online and play.",
    hero_badge: "Real-time availability · No double bookings",
    search_placeholder: "Search by name or neighborhood",
    all_cities: "All cities",
    all_types: "All types",
    society: "Society",
    futsal: "Futsal",
    campo: "Open field",
    from_price: "from",
    book_now: "Book now",
    no_fields: "No fields found",
    per_hour: "per slot",
    choose_date: "Pick a day",
    choose_time: "Pick a time",
    available: "Available",
    booked: "Booked",
    blocked: "Blocked",
    past: "Past",
    summary: "Booking summary",
    field: "Field",
    date: "Date",
    time: "Time",
    price: "Price",
    payment_method: "Payment method",
    pay_online: "Pay online (card/Pix via Stripe)",
    pay_on_site: "Pay at the venue",
    confirm_booking: "Confirm booking",
    login_to_book: "Sign in to book",
    what_included: "What's included",
    address: "Address",
    cancellation_policy: "Cancellation policy",
    cancel_policy_text: "Cancel up to {h}h before for a {p}% refund",
    my_bookings: "My bookings",
    no_bookings: "You have no bookings yet",
    cancel_booking: "Cancel booking",
    pay_now: "Pay now",
    status_confirmed: "Confirmed",
    status_pending_payment: "Pending payment",
    status_canceled: "Canceled",
    booking_confirmed: "Booking confirmed!",
    booking_cancelled: "Booking canceled",
    confirm_cancel_title: "Cancel this booking?",
    confirm: "Confirm",
    back: "Back",
    agenda: "Agenda",
    fields_tab: "My fields",
    revenue_tab: "Revenue",
    subscription_tab: "Subscription",
    add_field: "Add field",
    edit_field: "Edit field",
    manual_block: "Block time slot",
    block_reason: "Reason (maintenance, event...)",
    block_created: "Time slot blocked",
    block_removed: "Block removed",
    remove_block: "Remove block",
    blocks_today: "Blocks for this day",
    no_slots: "No time slots configured for this day",
    revenue_month: "Monthly revenue",
    bookings_count: "Bookings",
    online: "Online",
    on_site: "On site",
    subscription_status: "Subscription status",
    trialing: "Free trial",
    active: "Active",
    past_due: "Past due",
    canceled: "Canceled",
    none: "No subscription",
    trial_days_left: "trial days left",
    trial_expired: "Your free trial is over. Subscribe to keep receiving bookings.",
    subscribe_now: "Subscribe now",
    renews_at: "Renews on",
    plan_includes: "Full dashboard, unlimited bookings and online payments.",
    admin_metrics: "Platform metrics",
    owners: "Field owners",
    active_subs: "Active subscriptions",
    trialing_subs: "Trialing",
    past_due_subs: "Past due",
    fields_total: "Active fields",
    bookings_month: "Bookings this month",
    mrr: "Monthly recurring revenue",
    gmv_month: "Bookings volume this month",
    owner_name: "Owner",
    subscription: "Subscription",
    actions: "Actions",
    deactivate: "Deactivate",
    activate: "Activate",
    inactive: "Deactivated",
    demo_customer: "Sign in as Player",
    demo_owner: "Sign in as Field Owner",
    demo_admin: "Sign in as Admin",
    email: "Email",
    password: "Password",
    name: "Name",
    phone: "Phone (WhatsApp)",
    i_am: "I am a",
    customer_role: "Player (I want to book)",
    owner_role: "Field owner",
    forgot_password: "Forgot my password",
    send_reset: "Send reset link",
    reset_sent: "If that email is registered, a reset link was sent.",
    new_password: "New password",
    reset_password: "Reset password",
    back_to_login: "Back to sign in",
    payment_success: "Payment confirmed!",
    payment_processing: "Confirming payment...",
    payment_failed: "Could not confirm payment",
    payment_cancelled: "Payment canceled",
    payment_cancelled_text: "You canceled checkout. Your booking was not confirmed.",
    go_bookings: "View my bookings",
    go_home: "Back to home",
    save: "Save",
    delete: "Delete",
    cancel: "Cancel",
    field_name: "Field name",
    city: "City",
    neighborhood: "Neighborhood",
    description: "Description",
    photos: "Photos (one URL per line)",
    slot_duration: "Slot duration (min)",
    weekly_schedule: "Weekly schedule",
    add_window: "Add window",
    cancel_hours: "Cancel up to (hours before)",
    refund_percent: "Refund (%)",
    accepts: "Accepted payments",
    amenities_label: "Included items",
    field_saved: "Field saved!",
    field_deleted: "Field deleted",
    booking_cancelled_by_owner: "Booking canceled and refunded (if paid online)",
    amenity_bola: "Ball",
    amenity_coletes: "Bibs",
    amenity_iluminacao: "Floodlights",
    amenity_vestiario: "Locker rooms",
    amenity_arbitragem: "Referee",
    amenity_estacionamento: "Parking",
    amenity_churrasqueira: "BBQ area",
    amenity_bar: "Bar/Snacks",
    select_field: "Select a field",
    notifications: "Notifications",
    no_notifications: "No notifications",
    mark_read: "Mark all as read",
    days: ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"],
    step_field: "1. Field",
    step_time: "2. Time",
    step_pay: "3. Payment",
    owner_cta_title: "Own a pitch or court?",
    owner_cta_text: "Manage schedule, bookings and payments in one place. 7-day free trial.",
    owner_cta_button: "List my field",
    continue_with_google: "Continue with Google",
    or_divider: "or",
  },
};

const LangContext = createContext(null);

export function LangProvider({ children }) {
  const [lang, setLang] = useState(() => localStorage.getItem("campomark_lang") || "pt");
  const change = (l) => {
    setLang(l);
    localStorage.setItem("campomark_lang", l);
  };
  const t = (key, vars) => {
    let s = dict[lang]?.[key] ?? dict.pt[key] ?? key;
    if (typeof s === "string" && vars) {
      Object.entries(vars).forEach(([k, v]) => { s = s.replace(`{${k}}`, v); });
    }
    return s;
  };
  return <LangContext.Provider value={{ lang, setLang: change, t }}>{children}</LangContext.Provider>;
}

export const useLang = () => useContext(LangContext);
