import { createContext, useContext, useEffect, useState } from "react";
import api from "../lib/api";

export const COUNTRIES = [
  { code: "BR", name: "Brasil", currency: "brl" },
  { code: "US", name: "United States", currency: "usd" },
  { code: "PT", name: "Portugal", currency: "eur" },
  { code: "ES", name: "España", currency: "eur" },
  { code: "AR", name: "Argentina", currency: "ars" },
  { code: "MX", name: "México", currency: "mxn" },
  { code: "CO", name: "Colombia", currency: "cop" },
  { code: "CL", name: "Chile", currency: "clp" },
  { code: "GB", name: "United Kingdom", currency: "gbp" },
  { code: "DE", name: "Deutschland", currency: "eur" },
  { code: "FR", name: "France", currency: "eur" },
  { code: "IT", name: "Italia", currency: "eur" },
];

export const currencyForCountry = (code) =>
  (COUNTRIES.find((c) => c.code === code) || {}).currency || "brl";

export const money = (v, currency = "brl") => {
  try {
    return new Intl.NumberFormat("pt-BR", {
      style: "currency", currency: (currency || "brl").toUpperCase(),
    }).format(v ?? 0);
  } catch {
    return `${(v ?? 0).toFixed(2)} ${(currency || "").toUpperCase()}`;
  }
};

const dict = {
  pt: {
    app_name: "CampoMark",
    nav_explore: "Explorar campos",
    nav_my_bookings: "Minhas reservas",
    nav_dashboard: "Painel do dono",
    nav_admin: "Administração",
    login: "Entrar",
    logout: "Sair",
    register: "Criar conta",
    hero_title: "Reserve seu campo em 3 passos",
    hero_subtitle: "Encontre quadras society, futsal e campos abertos perto de você. Escolha o horário, pague online e jogue.",
    hero_badge: "Agenda em tempo real · Sem conflito de horários",
    search_placeholder: "Buscar por nome ou bairro",
    all_cities: "Todas as cidades",
    all_types: "Todos os tipos",
    all_countries: "Todos os países",
    country: "País",
    society: "Society",
    futsal: "Futsal",
    campo: "Campo aberto",
    from_price: "a partir de",
    book_now: "Reservar",
    no_fields: "Nenhum campo encontrado",
    no_fields_in_country: "Ainda não temos campos em {país} — cadastre o seu campo agora!",
    per_hour: "por horário",
    choose_date: "Escolha o dia",
    choose_time: "Escolha o horário",
    available: "Disponível",
    booked: "Reservado",
    blocked: "Bloqueado",
    past: "Passado",
    summary: "Resumo da reserva",
    field: "Campo",
    date: "Data",
    time: "Horário",
    price: "Valor",
    payment_method: "Forma de pagamento",
    pay_online: "Pagar online (cartão/Pix via Stripe)",
    pay_on_site: "Pagar no local",
    confirm_booking: "Confirmar reserva",
    login_to_book: "Entre para reservar",
    what_included: "O que está incluso",
    address: "Endereço",
    cancellation_policy: "Política de cancelamento",
    cancel_policy_text: "Cancelamento até {h}h antes com reembolso de {p}%",
    my_bookings: "Minhas reservas",
    no_bookings: "Você ainda não tem reservas",
    cancel_booking: "Cancelar reserva",
    pay_now: "Pagar agora",
    status_confirmed: "Confirmada",
    status_pending_payment: "Aguardando pagamento",
    status_canceled: "Cancelada",
    booking_confirmed: "Reserva confirmada!",
    booking_cancelled: "Reserva cancelada",
    confirm_cancel_title: "Cancelar esta reserva?",
    confirm: "Confirmar",
    back: "Voltar",
    agenda: "Agenda",
    fields_tab: "Meus campos",
    revenue_tab: "Faturamento",
    subscription_tab: "Assinatura",
    add_field: "Adicionar campo",
    edit_field: "Editar campo",
    manual_block: "Bloquear horário",
    block_reason: "Motivo (manutenção, evento...)",
    block_created: "Horário bloqueado",
    block_removed: "Bloqueio removido",
    remove_block: "Remover bloqueio",
    blocks_today: "Bloqueios do dia",
    no_slots: "Sem horários configurados para este dia",
    revenue_month: "Faturamento do mês",
    bookings_count: "Reservas",
    online: "Online",
    on_site: "No local",
    subscription_status: "Status da assinatura",
    trialing: "Teste grátis",
    active: "Ativa",
    past_due: "Em atraso",
    canceled: "Cancelada",
    none: "Sem assinatura",
    trial_days_left: "dias de teste restantes",
    trial_expired: "Seu teste grátis terminou. Assine para continuar recebendo reservas.",
    subscribe_now: "Assinar agora",
    renews_at: "Renova em",
    plan_includes: "Painel completo, reservas ilimitadas e pagamentos online.",
    admin_metrics: "Métricas da plataforma",
    owners: "Donos de campo",
    active_subs: "Assinaturas ativas",
    trialing_subs: "Em teste grátis",
    past_due_subs: "Em atraso",
    fields_total: "Campos ativos",
    bookings_month: "Reservas no mês",
    mrr: "Receita mensal (MRR)",
    gmv_month: "Reservas movimentadas no mês",
    owner_name: "Dono",
    subscription: "Assinatura",
    actions: "Ações",
    deactivate: "Desativar",
    activate: "Ativar",
    inactive: "Desativado",
    demo_customer: "Entrar como Jogador",
    demo_owner: "Entrar como Dono de Arena",
    demo_admin: "Entrar como Admin",
    email: "E-mail",
    password: "Senha",
    name: "Nome",
    phone: "Telefone (WhatsApp)",
    i_am: "Eu sou",
    customer_role: "Jogador (quero reservar)",
    owner_role: "Dono de campo",
    forgot_password: "Esqueci minha senha",
    send_reset: "Enviar link de redefinição",
    reset_sent: "Se esse e-mail estiver cadastrado, enviamos o link.",
    new_password: "Nova senha",
    reset_password: "Redefinir senha",
    back_to_login: "Voltar para o login",
    payment_success: "Pagamento confirmado!",
    payment_processing: "Confirmando pagamento...",
    payment_failed: "Não foi possível confirmar o pagamento",
    payment_cancelled: "Pagamento cancelado",
    payment_cancelled_text: "Você cancelou o checkout. Sua reserva não foi confirmada.",
    go_bookings: "Ver minhas reservas",
    go_home: "Voltar ao início",
    save: "Salvar",
    delete: "Excluir",
    cancel: "Cancelar",
    field_name: "Nome do campo",
    city: "Cidade",
    neighborhood: "Bairro",
    description: "Descrição",
    photos: "Fotos (uma URL por linha)",
    slot_duration: "Duração de cada reserva (min)",
    weekly_schedule: "Grade semanal de horários",
    add_window: "Adicionar faixa",
    cancel_hours: "Cancelamento até (horas antes)",
    refund_percent: "Reembolso (%)",
    accepts: "Pagamentos aceitos",
    amenities_label: "Itens inclusos",
    field_saved: "Campo salvo!",
    field_deleted: "Campo excluído",
    booking_cancelled_by_owner: "Reserva cancelada e reembolsada (se paga online)",
    amenity_bola: "Bola",
    amenity_coletes: "Coletes",
    amenity_iluminacao: "Iluminação",
    amenity_vestiario: "Vestiário",
    amenity_arbitragem: "Arbitragem",
    amenity_estacionamento: "Estacionamento",
    amenity_churrasqueira: "Churrasqueira",
    amenity_bar: "Bar/Lanchonete",
    select_field: "Selecione o campo",
    notifications: "Notificações",
    no_notifications: "Sem notificações",
    mark_read: "Marcar como lidas",
    step_field: "1. Campo",
    step_time: "2. Horário",
    step_pay: "3. Pagamento",
    owner_cta_title: "Tem um campo ou quadra?",
    owner_cta_text: "Gerencie agenda, reservas e pagamentos em um só lugar. Teste grátis por 7 dias.",
    owner_cta_button: "Cadastrar meu campo",
    continue_with_google: "Continuar com Google",
    or_divider: "ou",
    mark_as_paid: "Marcar como pago",
    marked_paid: "Pagamento registrado",
    payment_pending_local: "Pagamento pendente (no local)",
    paid: "Pago",
    receipt: "Comprovante",
    view_receipt: "Ver comprovante",
    upload_receipt: "Anexar comprovante",
    no_receipt: "Sem comprovante",
    receipt_uploaded: "Comprovante anexado",
    receipt_auto_stripe: "Comprovante automático (Stripe)",
    view_as_owner: "Ver como dono",
    edit_profile: "Editar perfil",
    profile_updated: "Perfil atualizado",
    warn_owner: "Enviar aviso",
    warning_message: "Mensagem do aviso",
    send_warning: "Enviar aviso",
    warning_sent: "Aviso enviado ao dono",
    suspend_account: "Suspender conta",
    ban_account: "Banir conta",
    delete_account: "Deletar conta",
    activate_account: "Reativar conta",
    account_suspended: "Conta suspensa",
    account_banned: "Conta banida",
    account_deleted: "Conta deletada",
    account_activated: "Conta reativada",
    banned: "Banido",
    suspended: "Suspenso",
    confirm_destructive: "Tem certeza? Essa ação fica registrada no log de auditoria.",
    audit_log: "Log de auditoria",
    action: "Ação",
    actor: "Autor",
    when: "Quando",
    target: "Alvo",    make_private: "Tornar privado",
    make_public: "Tornar público",
    hidden_field: "Oculto da busca",
    field_hidden: "Campo ocultado da busca pública",
    field_visible: "Campo visível na busca pública",
    theme_toggle: "Alternar tema",
    recent_bookings: "Reservas recentes",
    refunded: "Reembolsado",
    deleted: "Deletado",
  },
  en: {
    app_name: "CampoMark",
    nav_explore: "Explore fields",
    nav_my_bookings: "My bookings",
    nav_dashboard: "Owner dashboard",
    nav_admin: "Administration",
    login: "Sign in",
    logout: "Sign out",
    register: "Sign up",
    hero_title: "Book your pitch in 3 steps",
    hero_subtitle: "Find society, futsal and open fields near you. Pick a time, pay online and play.",
    hero_badge: "Real-time availability · No double bookings",
    search_placeholder: "Search by name or neighborhood",
    all_cities: "All cities",
    all_types: "All types",
    all_countries: "All countries",
    country: "Country",
    society: "Society",
    futsal: "Futsal",
    campo: "Open field",
    from_price: "from",
    book_now: "Book now",
    no_fields: "No fields found",
    no_fields_in_country: "No fields in {país} yet — list your field now!",
    per_hour: "per slot",
    choose_date: "Pick a day",
    choose_time: "Pick a time",
    available: "Available",
    booked: "Booked",
    blocked: "Blocked",
    past: "Past",
    summary: "Booking summary",
    field: "Field",
    date: "Date",
    time: "Time",
    price: "Price",
    payment_method: "Payment method",
    pay_online: "Pay online (card/Pix via Stripe)",
    pay_on_site: "Pay at the venue",
    confirm_booking: "Confirm booking",
    login_to_book: "Sign in to book",
    what_included: "What's included",
    address: "Address",
    cancellation_policy: "Cancellation policy",
    cancel_policy_text: "Cancel up to {h}h before for a {p}% refund",
    my_bookings: "My bookings",
    no_bookings: "You have no bookings yet",
    cancel_booking: "Cancel booking",
    pay_now: "Pay now",
    status_confirmed: "Confirmed",
    status_pending_payment: "Pending payment",
    status_canceled: "Canceled",
    booking_confirmed: "Booking confirmed!",
    booking_cancelled: "Booking canceled",
    confirm_cancel_title: "Cancel this booking?",
    confirm: "Confirm",
    back: "Back",
    agenda: "Agenda",
    fields_tab: "My fields",
    revenue_tab: "Revenue",
    subscription_tab: "Subscription",
    add_field: "Add field",
    edit_field: "Edit field",
    manual_block: "Block time slot",
    block_reason: "Reason (maintenance, event...)",
    block_created: "Time slot blocked",
    block_removed: "Block removed",
    remove_block: "Remove block",
    blocks_today: "Blocks for this day",
    no_slots: "No time slots configured for this day",
    revenue_month: "Monthly revenue",
    bookings_count: "Bookings",
    online: "Online",
    on_site: "On site",
    subscription_status: "Subscription status",
    trialing: "Free trial",
    active: "Active",
    past_due: "Past due",
    canceled: "Canceled",
    none: "No subscription",
    trial_days_left: "trial days left",
    trial_expired: "Your free trial is over. Subscribe to keep receiving bookings.",
    subscribe_now: "Subscribe now",
    renews_at: "Renews on",
    plan_includes: "Full dashboard, unlimited bookings and online payments.",
    admin_metrics: "Platform metrics",
    owners: "Field owners",
    active_subs: "Active subscriptions",
    trialing_subs: "Trialing",
    past_due_subs: "Past due",
    fields_total: "Active fields",
    bookings_month: "Bookings this month",
    mrr: "Monthly recurring revenue",
    gmv_month: "Bookings volume this month",
    owner_name: "Owner",
    subscription: "Subscription",
    actions: "Actions",
    deactivate: "Deactivate",
    activate: "Activate",
    inactive: "Deactivated",
    demo_customer: "Sign in as Player",
    demo_owner: "Sign in as Field Owner",
    demo_admin: "Sign in as Admin",
    email: "Email",
    password: "Password",
    name: "Name",
    phone: "Phone (WhatsApp)",
    i_am: "I am a",
    customer_role: "Player (I want to book)",
    owner_role: "Field owner",
    forgot_password: "Forgot my password",
    send_reset: "Send reset link",
    reset_sent: "If that email is registered, a reset link was sent.",
    new_password: "New password",
    reset_password: "Reset password",
    back_to_login: "Back to sign in",
    payment_success: "Payment confirmed!",
    payment_processing: "Confirming payment...",
    payment_failed: "Could not confirm payment",
    payment_cancelled: "Payment canceled",
    payment_cancelled_text: "You canceled checkout. Your booking was not confirmed.",
    go_bookings: "View my bookings",
    go_home: "Back to home",
    save: "Save",
    delete: "Delete",
    cancel: "Cancel",
    field_name: "Field name",
    city: "City",
    neighborhood: "Neighborhood",
    description: "Description",
    photos: "Photos (one URL per line)",
    slot_duration: "Slot duration (min)",
    weekly_schedule: "Weekly schedule",
    add_window: "Add window",
    cancel_hours: "Cancel up to (hours before)",
    refund_percent: "Refund (%)",
    accepts: "Accepted payments",
    amenities_label: "Included items",
    field_saved: "Field saved!",
    field_deleted: "Field deleted",
    booking_cancelled_by_owner: "Booking canceled and refunded (if paid online)",
    amenity_bola: "Ball",
    amenity_coletes: "Bibs",
    amenity_iluminacao: "Floodlights",
    amenity_vestiario: "Locker rooms",
    amenity_arbitragem: "Referee",
    amenity_estacionamento: "Parking",
    amenity_churrasqueira: "BBQ area",
    amenity_bar: "Bar/Snacks",
    select_field: "Select a field",
    notifications: "Notifications",
    no_notifications: "No notifications",
    mark_read: "Mark all as read",
    step_field: "1. Field",
    step_time: "2. Time",
    step_pay: "3. Payment",
    owner_cta_title: "Own a pitch or court?",
    owner_cta_text: "Manage schedule, bookings and payments in one place. 7-day free trial.",
    owner_cta_button: "List my field",
    continue_with_google: "Continue with Google",
    or_divider: "or",
    mark_as_paid: "Mark as paid",
    marked_paid: "Payment recorded",
    payment_pending_local: "Payment pending (on site)",
    paid: "Paid",
    receipt: "Receipt",
    view_receipt: "View receipt",
    upload_receipt: "Upload receipt",
    no_receipt: "No receipt",
    receipt_uploaded: "Receipt uploaded",
    receipt_auto_stripe: "Automatic receipt (Stripe)",
    view_as_owner: "View as owner",
    edit_profile: "Edit profile",
    profile_updated: "Profile updated",
    warn_owner: "Send warning",
    warning_message: "Warning message",
    send_warning: "Send warning",
    warning_sent: "Warning sent to owner",
    suspend_account: "Suspend account",
    ban_account: "Ban account",
    delete_account: "Delete account",
    activate_account: "Reactivate account",
    account_suspended: "Account suspended",
    account_banned: "Account banned",
    account_deleted: "Account deleted",
    account_activated: "Account reactivated",
    banned: "Banned",
    suspended: "Suspended",
    confirm_destructive: "Are you sure? This action is recorded in the audit log.",
    audit_log: "Audit log",
    action: "Action",
    actor: "Actor",
    when: "When",
    target: "Target",
    make_private: "Make private",
    make_public: "Make public",
    hidden_field: "Hidden from search",
    field_hidden: "Field hidden from public search",
    field_visible: "Field visible in public search",
    theme_toggle: "Toggle theme",
    recent_bookings: "Recent bookings",
    refunded: "Refunded",
    deleted: "Deleted",
  },
  es: {
    app_name: "CampoMark",
    nav_explore: "Explorar canchas",
    nav_my_bookings: "Mis reservas",
    nav_dashboard: "Panel del dueño",
    nav_admin: "Administración",
    login: "Iniciar sesión",
    logout: "Salir",
    register: "Crear cuenta",
    hero_title: "Reserva tu cancha en 3 pasos",
    hero_subtitle: "Encuentra canchas de society, futsal y campos abiertos cerca de ti. Elige el horario, paga online y juega.",
    hero_badge: "Agenda en tiempo real · Sin conflictos de horario",
    search_placeholder: "Buscar por nombre o barrio",
    all_cities: "Todas las ciudades",
    all_types: "Todos los tipos",
    all_countries: "Todos los países",
    country: "País",
    society: "Society",
    futsal: "Futsal",
    campo: "Campo abierto",
    from_price: "desde",
    book_now: "Reservar",
    no_fields: "No se encontraron canchas",
    no_fields_in_country: "¡Aún no tenemos canchas en {país} — registra la tuya ahora!",
    per_hour: "por horario",
    choose_date: "Elige el día",
    choose_time: "Elige el horario",
    available: "Disponible",
    booked: "Reservado",
    blocked: "Bloqueado",
    past: "Pasado",
    summary: "Resumen de la reserva",
    field: "Cancha",
    date: "Fecha",
    time: "Horario",
    price: "Precio",
    payment_method: "Método de pago",
    pay_online: "Pagar online (tarjeta/Pix vía Stripe)",
    pay_on_site: "Pagar en el lugar",
    confirm_booking: "Confirmar reserva",
    login_to_book: "Inicia sesión para reservar",
    what_included: "Qué está incluido",
    address: "Dirección",
    cancellation_policy: "Política de cancelación",
    cancel_policy_text: "Cancelación hasta {h}h antes con reembolso del {p}%",
    my_bookings: "Mis reservas",
    no_bookings: "Aún no tienes reservas",
    cancel_booking: "Cancelar reserva",
    pay_now: "Pagar ahora",
    status_confirmed: "Confirmada",
    status_pending_payment: "Pago pendiente",
    status_canceled: "Cancelada",
    booking_confirmed: "¡Reserva confirmada!",
    booking_cancelled: "Reserva cancelada",
    confirm_cancel_title: "¿Cancelar esta reserva?",
    confirm: "Confirmar",
    back: "Volver",
    agenda: "Agenda",
    fields_tab: "Mis canchas",
    revenue_tab: "Facturación",
    subscription_tab: "Suscripción",
    add_field: "Agregar cancha",
    edit_field: "Editar cancha",
    manual_block: "Bloquear horario",
    block_reason: "Motivo (mantenimiento, evento...)",
    block_created: "Horario bloqueado",
    block_removed: "Bloqueo eliminado",
    remove_block: "Eliminar bloqueo",
    blocks_today: "Bloqueos del día",
    no_slots: "Sin horarios configurados para este día",
    revenue_month: "Facturación del mes",
    bookings_count: "Reservas",
    online: "Online",
    on_site: "En el lugar",
    subscription_status: "Estado de suscripción",
    trialing: "Prueba gratis",
    active: "Activa",
    past_due: "Vencida",
    canceled: "Cancelada",
    none: "Sin suscripción",
    trial_days_left: "días de prueba restantes",
    trial_expired: "Tu prueba gratis terminó. Suscríbete para seguir recibiendo reservas.",
    subscribe_now: "Suscribirse ahora",
    renews_at: "Renueva el",
    plan_includes: "Panel completo, reservas ilimitadas y pagos online.",
    admin_metrics: "Métricas de la plataforma",
    owners: "Dueños de canchas",
    active_subs: "Suscripciones activas",
    trialing_subs: "En prueba gratis",
    past_due_subs: "Vencidas",
    fields_total: "Canchas activas",
    bookings_month: "Reservas del mes",
    mrr: "Ingresos mensuales (MRR)",
    gmv_month: "Volumen de reservas del mes",
    owner_name: "Dueño",
    subscription: "Suscripción",
    actions: "Acciones",
    deactivate: "Desactivar",
    activate: "Activar",
    inactive: "Desactivado",
    demo_customer: "Entrar como Jugador",
    demo_owner: "Entrar como Dueño",
    demo_admin: "Entrar como Admin",
    email: "Correo electrónico",
    password: "Contraseña",
    name: "Nombre",
    phone: "Teléfono (WhatsApp)",
    i_am: "Soy",
    customer_role: "Jugador (quiero reservar)",
    owner_role: "Dueño de cancha",
    forgot_password: "Olvidé mi contraseña",
    send_reset: "Enviar enlace de restablecimiento",
    reset_sent: "Si ese correo está registrado, enviamos el enlace.",
    new_password: "Nueva contraseña",
    reset_password: "Restablecer contraseña",
    back_to_login: "Volver al inicio de sesión",
    payment_success: "¡Pago confirmado!",
    payment_processing: "Confirmando pago...",
    payment_failed: "No se pudo confirmar el pago",
    payment_cancelled: "Pago cancelado",
    payment_cancelled_text: "Cancelaste el checkout. Tu reserva no fue confirmada.",
    go_bookings: "Ver mis reservas",
    go_home: "Volver al inicio",
    save: "Guardar",
    delete: "Eliminar",
    cancel: "Cancelar",
    field_name: "Nombre de la cancha",
    city: "Ciudad",
    neighborhood: "Barrio",
    description: "Descripción",
    photos: "Fotos (una URL por línea)",
    slot_duration: "Duración de cada reserva (min)",
    weekly_schedule: "Horario semanal",
    add_window: "Agregar franja",
    cancel_hours: "Cancelación hasta (horas antes)",
    refund_percent: "Reembolso (%)",
    accepts: "Pagos aceptados",
    amenities_label: "Elementos incluidos",
    field_saved: "¡Cancha guardada!",
    field_deleted: "Cancha eliminada",
    booking_cancelled_by_owner: "Reserva cancelada y reembolsada (si fue pagada online)",
    amenity_bola: "Balón",
    amenity_coletes: "Pecheras",
    amenity_iluminacao: "Iluminación",
    amenity_vestiario: "Vestuarios",
    amenity_arbitragem: "Arbitraje",
    amenity_estacionamento: "Estacionamiento",
    amenity_churrasqueira: "Parrilla",
    amenity_bar: "Bar/Cafetería",
    select_field: "Selecciona la cancha",
    notifications: "Notificaciones",
    no_notifications: "Sin notificaciones",
    mark_read: "Marcar como leídas",
    step_field: "1. Cancha",
    step_time: "2. Horario",
    step_pay: "3. Pago",
    owner_cta_title: "¿Tienes una cancha?",
    owner_cta_text: "Gestiona agenda, reservas y pagos en un solo lugar. Prueba gratis por 7 días.",
    owner_cta_button: "Registrar mi cancha",
    continue_with_google: "Continuar con Google",
    or_divider: "o",
    mark_as_paid: "Marcar como pagado",
    marked_paid: "Pago registrado",
    payment_pending_local: "Pago pendiente (en el lugar)",
    paid: "Pagado",
    receipt: "Comprobante",
    view_receipt: "Ver comprobante",
    upload_receipt: "Adjuntar comprobante",
    no_receipt: "Sin comprobante",
    receipt_uploaded: "Comprobante adjuntado",
    receipt_auto_stripe: "Comprobante automático (Stripe)",
    view_as_owner: "Ver como dueño",
    edit_profile: "Editar perfil",
    profile_updated: "Perfil actualizado",
    warn_owner: "Enviar aviso",
    warning_message: "Mensaje del aviso",
    send_warning: "Enviar aviso",
    warning_sent: "Aviso enviado al dueño",
    suspend_account: "Suspender cuenta",
    ban_account: "Banear cuenta",
    delete_account: "Eliminar cuenta",
    activate_account: "Reactivar cuenta",
    account_suspended: "Cuenta suspendida",
    account_banned: "Cuenta baneada",
    account_deleted: "Cuenta eliminada",
    account_activated: "Cuenta reactivada",
    banned: "Baneado",
    suspended: "Suspendido",
    confirm_destructive: "¿Estás seguro? Esta acción queda registrada en el log de auditoría.",
    audit_log: "Log de auditoría",
    action: "Acción",
    actor: "Autor",
    when: "Cuándo",
    target: "Objetivo",
    make_private: "Hacer privada",
    make_public: "Hacer pública",
    hidden_field: "Oculta de la búsqueda",
    field_hidden: "Cancha ocultada de la búsqueda pública",
    field_visible: "Cancha visible en la búsqueda pública",
    theme_toggle: "Cambiar tema",
    recent_bookings: "Reservas recientes",
    refunded: "Reembolsado",
    deleted: "Eliminado",
  },
};

const LangContext = createContext(null);

function detectBrowserLang() {
  const nav = (navigator.language || "pt").toLowerCase();
  if (nav.startsWith("pt")) return "pt";
  if (nav.startsWith("es")) return "es";
  return "en";
}

export function LangProvider({ children }) {
  // Manual choices are persisted; auto-detection never overwrites them.
  const [lang, setLangState] = useState(
    () => localStorage.getItem("campomark_lang") || detectBrowserLang()
  );
  const [country, setCountryState] = useState(
    () => localStorage.getItem("campomark_country") || null
  );

  useEffect(() => {
    if (!localStorage.getItem("campomark_country")) {
      api.get("/geo").then((r) => {
        if (r.data?.country) setCountryState(r.data.country);
      }).catch(() => {});
    }
  }, []);

  const setLang = (l) => {
    setLangState(l);
    localStorage.setItem("campomark_lang", l);
  };
  const setCountry = (c) => {
    setCountryState(c);
    if (c) localStorage.setItem("campomark_country", c);
    else localStorage.removeItem("campomark_country");
  };

  const t = (key, vars) => {
    let s = dict[lang]?.[key] ?? dict.pt[key] ?? key;
    if (typeof s === "string" && vars) {
      Object.entries(vars).forEach(([k, v]) => { s = s.replace(`{${k}}`, v); });
    }
    return s;
  };

  return (
    <LangContext.Provider value={{ lang, setLang, country, setCountry, t }}>
      {children}
    </LangContext.Provider>
  );
}

export const useLang = () => useContext(LangContext);
